name: Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: gradle

      - name: Setup and execute Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: spotlessCheck clean :ca-app:assemble

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: CurrentActivity.apk
          path: 'ca/app/build/outputs/apk/release/ca-app-release.apk'
